version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # фронт
      - "3001:3001" # бэк
    environment:
      GRAPHQL_PATH: graphql
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/myapp?authSource=admin
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: "true"
      NODE_ENV: development
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:3001/graphql
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
