version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      - GRAPHQL_PATH=${GRAPHQL_PATH}
      - PORT=${BACK_PORT}
      - BACK_PORT=${BACK_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - GRAPHQL_INTROSPECTION=${GRAPHQL_INTROSPECTION}
      - CORS_ORIGIN=*
      - CORS_CREDENTIALS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${BACK_PORT}/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GRAPHQL_URL=${NEXT_PUBLIC_GRAPHQL_URL}
      - NEXT_PUBLIC_GRAPHQL_CHECK_URL=${NEXT_PUBLIC_GRAPHQL_CHECK_URL}
    depends_on:
      back:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
