version: "3.8"

services:
  # MongoDB сервис
  mongodb:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=myapp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      - GRAPHQL_PATH=#{GRAPHQL_PATH}
      - PORT=${BACK_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - CORS_ORIGIN=*
      - CORS_CREDENTIALS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GRAPHQL_URL=${NEXT_PUBLIC_GRAPHQL_URL}
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
